// tailwind.config.ts
import { type Config } from "tailwindcss";

const config: Config = {
  darkMode: "class", // REQUIRED for toggling themes
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
    "./node_modules/@physiq/ui/**/*.{js,ts,jsx,tsx}",
  ],
  // safelist: [
  //   "bg-destructive",
  //   "text-white",
  //   "shadow-xs",
  //   "hover:bg-destructive/90",
  //   "focus-visible:ring-destructive/20",
  //   "bg-primary",
  //   "text-primary-foreground",
  //   "hover:bg-primary/90",
  //   "bg-secondary",
  //   "text-secondary-foreground",
  //   "hover:bg-secondary/80",
  //   "bg-background",
  //   "hover:bg-accent",
  //   "hover:text-accent-foreground",
  //   "text-primary",
  //   "hover:underline",
  //   "underline-offset-4",
  //   "border",
  //   "inline-flex",
  //   "items-center",
  //   "justify-center",
  //   "gap-2",
  //   "whitespace-nowrap",
  //   "rounded-md",
  //   "text-sm",
  //   "font-medium",
  //   "transition-all",
  //   "disabled:pointer-events-none",
  //   "disabled:opacity-50",
  //   "outline-none",
  //   "focus-visible:border-ring",
  //   "focus-visible:ring-ring/50",
  //   "focus-visible:ring-[3px]",
  //   "aria-invalid:ring-destructive/20",
  //   "aria-invalid:border-destructive",
  //   "h-8",
  //   "h-9",
  //   "h-10",
  //   "px-3",
  //   "px-4",
  //   "px-6",
  //   "py-1",
  //   "py-2",
  //   "gap-1.5",
  //   "size-9",
  //   "animate-spin",

  //   // Input component classes
  //   "flex",
  //   "w-full",
  //   "min-w-0",
  //   "border-input",
  //   "bg-transparent",
  //   "text-base",
  //   "placeholder:text-muted-foreground",
  //   "selection:bg-primary",
  //   "selection:text-primary-foreground",
  //   "disabled:cursor-not-allowed",
  //   "md:text-sm",
  //   "file:inline-flex",
  //   "file:h-7",
  //   "file:border-0",
  //   "file:bg-transparent",
  //   "file:text-sm",
  //   "file:font-medium",
  //   "file:text-foreground",
  //   "transition-[color,box-shadow]",

  //   // Dark mode variants
  //   "dark:bg-input/30",
  //   "dark:border-input",
  //   "dark:hover:bg-input/50",
  //   "dark:bg-destructive/60",
  //   "dark:focus-visible:ring-destructive/40",
  //   "dark:aria-invalid:ring-destructive/40",
  //   "dark:hover:bg-accent/50",
  // ],
  theme: {
    extend: {},
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
